"""empty message

Revision ID: 3736fa1357d2
Revises: 46b752d26c99
Create Date: 2025-04-06 01:16:25.676206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3736fa1357d2'
down_revision: Union[str, None] = '46b752d26c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'favorite', ['user_id'])
    op.add_column('favorite_item', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'favorite_item', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'favorite_item', 'favorite', ['favorite_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite_item', type_='foreignkey')
    op.drop_constraint(None, 'favorite_item', type_='foreignkey')
    op.drop_column('favorite_item', 'product_id')
    op.drop_constraint(None, 'favorite', type_='unique')
    # ### end Alembic commands ###
